#!/bin/bash
set -euo pipefail

# Install f1x, prophet, genprog, dependencies for Ubuntu 14.04 62bit

DOWNLOAD="wget --retry-connrefused --waitretry=1 --read-timeout=20 --timeout=15 --tries=5 --continue"

INSTALL="sudo apt-get -y install"

cd "$( dirname "${BASH_SOURCE[0]}" )"


echo Installing dependencies

$INSTALL git mercurial subversion build-essential
$INSTALL unzip time
$INSTALL libboost-filesystem-dev libboost-program-options-dev libboost-log-dev # f1x
$INSTALL psmisc # experiments scripts
$INSTALL zlib1g-dev libexplain-dev # prophet
$INSTALL gawk # libtiff
$INSTALL re2c bison # php
$INSTALL libglib2.0-dev libsqlite3-dev # lighttpd
$INSTALL texinfo # gmp
$INSTALL libffi-dev gtk-doc-tools libgtk2.0-dev libqt4-dev libgtk-3-dev libpcap-dev flex # wireshark
$INSTALL sa-compile # don't know why
$INSTALL libncurses5-dev # python
$INSTALL ocaml camlp4 ocaml-findlib # genprog
$INSTALL libcunit1-dev #fbc




echo Installing new CMake

$DOWNLOAD https://cmake.org/files/v3.7/cmake-3.7.1.tar.gz
tar xf cmake-3.7.1.tar.gz
(
    cd cmake-3.7.1
    ./bootstrap
    make
    sudo make install
)


echo Installing Clang+LLVM 3.8.1, building f1x

git clone https://github.com/mechtaev/f1x
$DOWNLOAD http://releases.llvm.org/3.8.1/clang+llvm-3.8.1-x86_64-linux-gnu-ubuntu-14.04.tar.xz
tar xf clang+llvm-3.8.1-x86_64-linux-gnu-ubuntu-14.04.tar.xz
(
    cd f1x
    mkdir build
    cd build
    cmake -DF1X_LLVM=$PWD/../../clang+llvm-3.8.1-x86_64-linux-gnu-ubuntu-14.04 ..
    make
)

PATH=/f1x-genprog-icse12/f1x/build/tools:$PATH

echo Installing Clang+LLVM 3.6.2, building prophet

$DOWNLOAD http://releases.llvm.org/3.6.2/clang+llvm-3.6.2-x86_64-linux-gnu-ubuntu-14.04.tar.xz
tar xf clang+llvm-3.6.2-x86_64-linux-gnu-ubuntu-14.04.tar.xz
(
    export PATH=$PWD/clang+llvm-3.6.2-x86_64-linux-gnu-ubuntu-14.04/bin:$PATH
    ./get-prophet
    cd prophet
    make
)
