#!/bin/bash
set -euo pipefail

# Usage: ./clone-mirror URL
#
# Download all GenProg-ICSE'12/Kali subjects from URL
#
# Original URL: http://rhino.csail.mit.edu/spr-rep/scenarios/

url="$1"

DOWNLOAD="wget --retry-connrefused --waitretry=1 --read-timeout=20 --timeout=15 --tries=5 --continue"

ROOT=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

for subject in `cat $ROOT/mirror.txt`; do
    $DOWNLOAD "$url/$subject"
done
