#!/usr/bin/env bash

set -euo pipefail

download () {
    wget --retry-connrefused --waitretry=1 --read-timeout=20 --timeout=15 --tries=5 --continue "$1"
}

require () {
    hash "$1" 2>/dev/null || { echo >&2 "I require $1 but it's not installed. Aborting."; exit 1; }
}

require wget

PROPHET_URL="http://www.cs.toronto.edu/~fanl/program_repair/prophet-rep/prophet-0.1-src.tar.gz"
PROPHET_ARCHIVE="prophet-0.1-src.tar.gz"


cd "$( dirname "${BASH_SOURCE[0]}" )"


download "$PROPHET_URL"
mkdir -p "prophet"
tar xf "$PROPHET_ARCHIVE" --directory "prophet" --strip-components=1

(
    cd "prophet"
    sed -i '/cp/d' benchmarks/php-deps/Makefile.am
    sed -i 's|ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/pcre-8.36.tar.gz|https://s3-ap-southeast-1.amazonaws.com/program-repair/pcre-8.36.tar.gz|' benchmarks/lighttpd-deps/Makefile.am
    autoreconf -f -i
    ./configure
    sed -i 's/-Werror/-Wno-error/g' src/Makefile
)
